- name: set env variable DEBIAN_FRONTEND
  shell: export DEBIAN_FRONTEND="noninteractive"

- name: Install ntp and iptables 
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=installed
  with_items:
    - ntp
    - iptables-persistent

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Create iptables directory
  file: path=/etc/iptables state=directory

- name: Insert iptables template
  template: src=iptables.j2 dest=/etc/iptables/rules.v4